management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'

server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.pasha: DEBUG

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
