# only for development, we shouldn't expose too much info and make if public visible by show-values
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: ALWAYS
  health:
    circuitbreakers:
      enabled: true

server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
  datasource:
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    platform: postgres
  database:
    driverClassName: org.postgresql.Driver
example:
  property: I AM THE DEFAULT

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

resilience4j.circuitbreaker:
  instances:
    licenseService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 15s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 10
      failureRateThreshold: 20
    organizationService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.bulkhead:
  instances:
    bulkheadLicenseService:
      maxWaitDuration: 2ms
      maxConcurrentCalls: 20

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadLicenseService:
      maxThreadPoolSize: 2
      coreThreadPoolSize: 1
      queueCapacity: 2

resilience4j.retry:
  instances:
    retryLicenseService:
      maxRetryAttempts: 3
      waitDuration: 2s
      retry-exceptions:
        - java.lang.Exception
