spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://postgres-service:5432/postgres?sslmode=disable
    password: '{cipher}ea172133fa9031358b08c827b2a4f55ba0afca2fe63263216db549f10abee00c'

