# only for development, we shouldn't expose too much info and make if public visible by show-values
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: ALWAYS
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

server:
  port: 8081

logging:
  level:
      org.springframework.web: WARN
      com.pasha: DEBUG
  pattern:
    level : "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  config: classpath:logback-spring.xml

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
  datasource:
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    platform: postgres
  database:
    driverClassName: org.postgresql.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          enable-observation: true
  jackson:
    serialization:
      indent-output: true

example:
  property: I AM THE DEFAULT

logstash.host: localhost:5000

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

